sudo: false # route your build to the container-based infrastructure for a faster build
rvm: 2.4.1
os: linux
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache:
  bundler: true
  directories:
  - vendor/bundle
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - ca-certificates
stages:
  - name: Test
    if: type != cron
  - name: Cron test and update
    if: type = cron AND branch = master

jobs:
  include:
    - &test-baseline
      stage: Test
      script:
        bundle exec rake
      
    - <<: *test-baseline
      script:
        bundle exec rake proof_external
    
    - stage: Cron test and update
      script:
      # - bundle exec rake
      - bundle exec rake build_date
      deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: true
        target_branch: myself
        on:
          all_branches: true # <== new!
  allow_failures:
    - stage: Test
      script:
        bundle exec rake proof_external
