title: 「從聖經看屬靈生命」 
email: zhangquan0126@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    兩年讀經笔记。材料由【西雅圖證道堂】東區國語堂提供。每日祷告和笔记与回应部分为本人所写。
baseurl: "/bible" # the subpath of your site, e.g. /blog
url: "https://zhangquan0126.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: zhangquan0126
repository: zhangquan0126/bible
repo: https://github.com/zhangquan0126/bible
lang: zh-Hant

github:
  is_project_page: false
  
# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
timezone: America/Chicago    

# Google Analytics
# google_analytics: UA—114680216-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
  - README.md
